/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jForm;
import controladores.GestionProductos;

/**
 *
 * @author marco
 */
public class BuscadorProducto extends javax.swing.JInternalFrame {

    GestionProductos buscador;
    
    public BuscadorProducto() {
        initComponents();

        tfNombre.setEnabled(false);
        tfiD.setEnabled(false);

        buscarPorNombre.setEnabled(false);
        buscarPorId.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnNombre = new javax.swing.JRadioButton();
        btnID = new javax.swing.JRadioButton();
        tfNombre = new javax.swing.JTextField();
        tfiD = new javax.swing.JTextField();
        buscarPorNombre = new javax.swing.JButton();
        buscarPorId = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();

        setClosable(true);
        setTitle("Búsqueda de productos");

        buttonGroup1.add(btnNombre);
        btnNombre.setText("Búsqueda por nombre");
        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnID);
        btnID.setText("Búsqueda por ID");
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        buscarPorNombre.setText("Buscar");
        buscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorNombreActionPerformed(evt);
            }
        });

        buscarPorId.setText("Buscar");
        buscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorIdActionPerformed(evt);
            }
        });

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Marca", "Precio venta", "Precio compra", "Cantidad en existencia", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNombre)
                            .addComponent(btnID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(tfiD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarPorId)
                            .addComponent(buscarPorNombre))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnID)
                    .addComponent(tfiD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorId))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed
        // Se activa el radioButton de búsqueda por nombre
        tfNombre.setEnabled(true);
        tfiD.setEnabled(false);

        buscarPorNombre.setEnabled(true);
        buscarPorId.setEnabled(false);
    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // Se activa el radioButton de búsqueda por ID
        tfNombre.setEnabled(false);
        tfiD.setEnabled(true);

        buscarPorNombre.setEnabled(false);
        buscarPorId.setEnabled(true);
    }//GEN-LAST:event_btnIDActionPerformed

    private void buscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorNombreActionPerformed
        // Búsqueda por nombre
        String nombre_producto = tfNombre.getText();
        
        buscador = new GestionProductos();
        tablaResultados.setModel(buscador.buscarPorNombre(nombre_producto));
    }//GEN-LAST:event_buscarPorNombreActionPerformed

    private void buscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorIdActionPerformed
        // Búsqueda por ID
        int id = Integer.parseInt(tfiD.getText());
        
        buscador = new GestionProductos();
        tablaResultados.setModel(buscador.buscarPorID(id));
        
    }//GEN-LAST:event_buscarPorIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnID;
    private javax.swing.JRadioButton btnNombre;
    private javax.swing.JButton buscarPorId;
    private javax.swing.JButton buscarPorNombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaResultados;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfiD;
    // End of variables declaration//GEN-END:variables
}
