/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jForm;

import controladores.ServicioDeArranque;
import controladores.TblCategoria;
import inventarioanlygui.Categoria;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class CrearCategoria extends javax.swing.JInternalFrame {

    ServicioDeArranque arranque;
    TblCategoria lista_categorias;
    Categoria categoria_nueva;
    public static DefaultComboBoxModel<String> actualizadorCBM;
    AgregarProducto app;
    
    public CrearCategoria() {
        lista_categorias = new TblCategoria();
        initComponents();
        actualizadorCBM = new DefaultComboBoxModel<>();
        arranque = new ServicioDeArranque(); 
        
       
    }

    public static DefaultComboBoxModel<String> getActualizadorCBM() {
        return actualizadorCBM;
    }

    public static void setActualizadorCBM(DefaultComboBoxModel<String> actualizadorCBM) {
        CrearCategoria.actualizadorCBM = actualizadorCBM;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();

        setClosable(true);
        setTitle("Nueva categoría");

        jLabel1.setText("Nombre de la nueva categoría:");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnCrear)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // Crear categorías
        
            
           categoria_nueva = new Categoria();
           String nuevaCat;
           nuevaCat = tfNombre.getText();
           categoria_nueva.setnombre(nuevaCat);
           
           lista_categorias.agregarCategoria(categoria_nueva);
           lista_categorias.insertarCategoriaEnDB(nuevaCat);
        
           actualizadorCBM = lista_categorias.actualizarCBM(nuevaCat);
           ServicioDeArranque.cmbCategorias.addElement(categoria_nueva.getnombre());
           
        
       
        
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
